### ISSUE TITLE
format on save

### ISSUE THREAD

**Issue by iu0v1** [focusaurus/atom-format-shell#1]
Hello.

May I ask to add this feature, please? :)

**Comment by focusaurus** [comment]
I can attempt to code it next time I have some time available. I'd also merge a pull request for it if you have time to code it up. I expect it will be mostly researching a similar package that already does this and mostly a copy/paste job of the necessary code for the preference boolean flag and the plugin behavior.

**Comment by iu0v1** [comment]
Sounds fairly. I will try to make it the next few days.

**Comment by focusaurus** [comment]
Looks great, thanks. I tested it locally and seems to work. For some reason atom won't show a "Settings" GUI for me on this package but it does respect my `config.cson` edits so dunno.

**Comment by iu0v1** [comment]
>For some reason atom won't show a "Settings" GUI for me

Tested on linux and windows - for me all seems fine. But on both installed atom 1.13.*. 
![0](https://cloud.githubusercontent.com/assets/1669027/23261109/87ec3712-f9dd-11e6-9a85-c29aa462d12b.png)

I will try to install the fresh version and test package on it. But will make it after work, most likely in the evening (by my utc :)). As I will finish - I will report about results.

**Comment by iu0v1** [comment]
>I will report about results

![0](https://cloud.githubusercontent.com/assets/1669027/23269783/5b42ab8e-f9fa-11e6-8608-3f0120353275.png)

1.14.3 - works for me.
