### ISSUE TITLE
Error on XUbuntu: need to run as root or suid

### ISSUE THREAD

**Issue by vlad2** [focusaurus/atom-format-shell#11]
Hello,

I have installed Atom as a Snap package on Ubuntu (X Ubuntu 19.04). I have installed shfmt as a Snap package on Ubuntu as well.  I have installed format-shell 2.2.1. 

Running shfmt from the command line works fine, I can format a shell script.
However, when running from Atom I get this error:

**need to run as root or suid**

(And the file is not formatted.)

I've seen that format-shell plugin tries to run shfmt with the parameters "-i 2". 

I don't understand why it gives that error message.

**Comment by focusaurus** [comment]
Hmm, you should not need to run atom nor shfmt as root. This is presumably something with snaps but unfortunately I don't know anything about snap packages so I can't really help. I suspect it's something to do with how the atom code from the snap interacts with system calls on the host system.
