### ISSUE TITLE
Incorrect formatting of IFS joined arrays in arithmetic expressions

### ISSUE THREAD

**Issue by leagris** [focusaurus/atom-format-shell#13]
- format-shell 2.2.1

Arrays joined using the `$IFS` environment variable (`${array[*]}`) within an arithmetic expression are, wrongly reformatted as `array[*]`.

```bash
#!/usr/bin/env sh
values=(10 3 7 5 2 4 8 3)
_OIFS=$IFS
IFS=\+
sum=$((${values[*]})) #42
IFS=$_OIFS
printf %d\\n $sum
```

`sum=$((${values[*]}))` is erroneously reformatted as `sum=$((values[*]))`

**Comment by focusaurus** [comment]
@leagris thanks for the report. Could you file that upstream in https://github.com/mvdan/sh please since that's the utility that actually does the formatting. This atom plugin just calls mvdan/sh to do the formatting.

**Comment by leagris** [comment]
Thank-you for the reminder!

My apologies, now reported as https://github.com/mvdan/sh/issues/616
