### ISSUE TITLE
Allow custom command line argument

### ISSUE THREAD

**Issue by 0rax** [focusaurus/atom-format-shell#4]
Hi, I just discovered your plugin after looking at the shfmt project though I would like to be able to parse custom cli argument to the binary such as `-bn` or `-ci` which can not be set using your current configuration.

Letting users add command line arguments by themselves would allow them to use newer shfmt feature without the need for you to add a custom tick box each time one is added.

Thanks

**Comment by focusaurus** [comment]
Thanks for the feature request. I'll have a look at it. I'll see how difficult explicit options would be and weigh that against letting users just configure the command line.

**Comment by focusaurus** [comment]
Fixed via e27bbf55786434c7dbd55857a5e835c7639adbd9. Try v2.1.0 and let me know how it works. I added GUI settings for these.

**Comment by 0rax** [comment]
Works perfectly ! Thanks
