### ISSUE TITLE
Is there a short cut for formatting a file?

### ISSUE THREAD

**Issue by fkromer** [focusaurus/atom-format-shell#6]
Is there a short cut to format the currently active file? (Instead of using `Packages -> Format Shell Script`)

**Comment by focusaurus** [comment]
There is a command with the name `format-shell:format` which you can bind to the keyboard short cut of your choosing.

**Comment by focusaurus** [comment]
Here's how I have mine bound for example (from keymap.cson)

```
'atom-workspace':
  'ctrl-. f s s': 'format-shell:format'
```
